final List<List<Map<String, String>>> wordLists = [
  // Lista de listas de pares de perguntas e respostas para cada nível do jogo.
  [
   {"pergunta":"Qual é o país com a maior população do mundo?","resposta":"CHINA"},
   {"pergunta":"Qual é o elemento químico com o símbolo \"Fe\"?","resposta":"FERRO"},
   {"pergunta":"Qual é o maior órgão interno do corpo humano?","resposta":"FIGADO"},
   {"pergunta":"Qual é o segundo planeta a partir do Sol?","resposta":"VENUS"},
   {"pergunta":"Qual é a cidade conhecida como \"Cidade Eterna\"?","resposta":"ROMA"},
   {"pergunta":"Qual é a cor do céu em um dia ensolarado?","resposta":"AZUL"},
   {"pergunta":"Qual é o símbolo químico do elemento oxigênio?","resposta":"O"},
   {"pergunta":"Quantos planetas existem em nosso sistema solar?","resposta":"OITO"},
   {"pergunta":"Quem escreveu a obra \"Dom Quixote\"?","resposta":"MIGUELDECERVANTES"},
   {"pergunta":"Qual é o processo pelo qual as plantas convertem luz solar em energia?","resposta":"FOTOSSINTESE"},
   {"pergunta":"Qual é o maior órgão do corpo humano?","resposta":"PELE"},
   {"pergunta":"Quem pintou a Mona Lisa?","resposta":"LEONARDODAVINCI"},
   {"pergunta":"Qual é a capital da Austrália?","resposta":"CANBERRA"},
   {"pergunta":"Quais são os três estados físicos da matéria?","resposta":"SOLIDOLIQUIDOGASOSO"},
   {"pergunta":"Quem é o autor de \"Romeu e Julieta\"?","resposta":"WILLIAMSHAKESPEARE"},
   {"pergunta":"Qual é o maior planeta do sistema solar?","resposta":"JUPITER"},
   {"pergunta":"Qual é o processo de transferência de calor através do movimento de um fluido?","resposta":"CONVECÇÃO"},
   {"pergunta":"Quem escreveu \"1984\"?","resposta":"GEORGEORWELL"},
   {"pergunta":"Qual é a capital do Canadá?","resposta":"OTTAWA"},
   {"pergunta":"Qual é a montanha mais alta do mundo?","resposta":"MONTEEVEREST"},
   {"pergunta":"Quem é conhecido como o \"pai da psicanálise\"?","resposta":"SIGMUNDFREUD"},
   {"pergunta":"Qual é a moeda oficial do Japão?","resposta":"IENE"},
   {"pergunta":"Qual é a maior artéria do corpo humano?","resposta":"AORTA"},
   {"pergunta":"Quem escreveu \"O Senhor dos Anéis\"?","resposta":"JRRTOLKIEN"},
   {"pergunta":"Qual é o processo de conversão de açúcares em álcool?","resposta":"FERMENTAÇÃO"},
   {"pergunta":"Quem foi o líder político sul-africano e ativista contra o apartheid?","resposta":"NELSONMANDELA"},
   {"pergunta":"Qual é o símbolo químico do ouro?","resposta":"AU"},
   {"pergunta":"Qual é a maior lua de Saturno?","resposta":"TITÃ"},
   {"pergunta":"Quem pintou \"A Noite Estrelada\"?","resposta":"VINCENTVANGOGH"},
   {"pergunta":"Qual é o processo de geração de energia nuclear a partir da fissão de átomos?","resposta":"ENERGIANUCLEAR"},
   {"pergunta":"Quem foi a primeira mulher a ganhar dois Prêmios Nobel em campos diferentes?","resposta":"MARIECURIE"}
   ,{"pergunta":"Qual é o rio mais longo do mundo?","resposta":"ORIONILO"},
   {"pergunta":"Quem é o autor de \"O Pequeno Príncipe\"?","resposta":"ANTOINEDESAINTEXUPERY"},
   {"pergunta":"Qual é o processo de conversão de gás em líquido?","resposta":"CONDENSAÇÃO"},
   {"pergunta":"Quem foi o primeiro homem a pisar na lua?","resposta":"NEILARMSTRONG"},
   {"pergunta":"Qual é o metal mais abundante na crosta terrestre?","resposta":"ALUMINIO"},
   {"pergunta":"Quem é conhecido como o \"pai da filosofia ocidental\"?","resposta":"SOCRATES"},
   {"pergunta":"Qual é a capital da França?","resposta":"PARIS"},
   {"pergunta":"Quem foi o cientista que formulou as leis do movimento e a lei da gravitação universal?","resposta":"ISAACNEWTON"},
   {"pergunta":"Qual é o processo de conversão de um sólido diretamente em gás, sem passar pelo estado líquido?","resposta":"SUBLIMAÇÃO"},
   {"pergunta":"Quem é a autora da série de livros \"Harry Potter\"?","resposta":"JKROWLING"},
   {"pergunta":"Qual é o elemento químico fundamental para a vida, encontrado em todas as moléculas orgânicas?","resposta":"CARBONO"},
   {"pergunta":"Quem foi o líder dos direitos civis dos Estados Unidos que proferiu o discurso \"Eu Tenho um Sonho\"?","resposta":"MARTINLUTHERKINGJR"},{"pergunta":"Qual é o processo de transformação direta de um gás em sólido?","resposta":"DEPOSIÇÃO"},
   {"pergunta":"Quem é o autor de \"A Origem das Espécies\" e defensor da teoria da evolução?","resposta":"CHARLESDARWIN"},
   {"pergunta":"Qual é o metal líquido à temperatura ambiente?","resposta":"MERCURIO"},
   {"pergunta":"Quem foi o pintor italiano renascentista que criou \"O Nascimento de Vênus\"?","resposta":"SANDROBOTTICELLI"},
   {"pergunta":"Qual é o processo de conversão de um líquido em gás na superfície?","resposta":"EVAPORAÇÃO"},
   {"pergunta":"Quem é considerado o pai da eletricidade?","resposta":"BENJAMINFRANKLIN"},
   {"pergunta":"Qual é a capital da Rússia?","resposta":"MOSCOU"},
   {"pergunta":"Quem foi o líder militar que se tornou imperador da França no início do século XIX?","resposta":"NAPOLEÃOBONAPARTE"},
   {"pergunta":"Qual é o processo de conversão de gás em plasma?","resposta":"IONIZAÇÃO"},
  ],
  [
   {"pergunta":"Quem é conhecido como o \"pai da geometria\"?","resposta":"EUCLIDES"},
   {"pergunta":"Qual é o segundo planeta a partir do Sol?","resposta":"VENUS"},
   {"pergunta":"Quem é o autor de \"A Divina Comédia\"?","resposta":"DANTEALIGHIERI"},
   {"pergunta":"Qual é o processo de conversão direta de um sólido em gás?","resposta":"SUBLIMAÇÃO"}
   ,{"pergunta":"Quem é considerado o \"pai da computação\"?","resposta":"ALANTURING"},
   {"pergunta":"Qual é o elemento químico mais abundante no universo?","resposta":"HIDROGENIO"},
   {"pergunta":"Quem escreveu \"O Alquimista\"?","resposta":"PAULOCOELHO"},
   {"pergunta":"Qual é o processo de conversão de um gás em líquido?","resposta":"CONDENSAÇÃO"},
   {"pergunta":"Quem foi o físico teórico que desenvolveu a teoria da relatividade?","resposta":"ALBERTEINSTEIN"},
   {"pergunta":"Qual é o menor planeta do sistema solar?","resposta":"MERCURIO"},
   {"pergunta":"Quem é o autor de \"Cem Anos de Solidão\"?","resposta":"GABRIELGARCIAMARQUEZ"},
   {"pergunta":"Qual é o processo de transferência de calor através de ondas eletromagnéticas?","resposta":"RADIAÇÃO"},
   {"pergunta":"Quem foi o líder político indiano que defendeu a independência da Índia?","resposta":"MAHATMAGANDHI"},
   {"pergunta":"Quem é a autora de \"Orgulho e Preconceito\"?","resposta":"JANEAUSTEN"},
   {"pergunta":"Qual é o processo de conversão de um líquido em gás?","resposta":"EVAPORAÇÃO"},
   {"pergunta":"Quem foi o pintor renascentista italiano conhecido por suas obras \"O Nascimento de Vênus\" e \"Primavera\"?","resposta":"SANDROBOTTICELLI"},
   {"pergunta":"Quem é o autor de \"Crime e Castigo\"?","resposta":"FIODORDOSTOIEVSKI"},
   {"pergunta":"Qual é o processo de conversão de um líquido em sólido?","resposta":"CRISTALIZAÇÃO"},
   {"pergunta":"Quem é considerado o \"pai da filosofia moderna\"?","resposta":"RENEDESCARTES"},
   {"pergunta":"Qual é o elemento químico com o símbolo \"Hg\"?","resposta":"MERCURIO"},
   {"pergunta":"Quem é o autor de \"O Retrato de Dorian Gray\"?","resposta":"OSCARWILDE"},
   {"pergunta":"Qual é o processo de conversão de um sólido diretamente em gás, sem passar pelo estado líquido?","resposta":"SUBLIMAÇÃO"},
   {"pergunta":"Quem é conhecido como o \"pai da biologia\"?","resposta":"ARISTOTELES"},
   {"pergunta":"Qual é o elemento químico com o símbolo \"Ag\"?","resposta":"PRATA"},
   {"pergunta":"Quem é o autor de \"Guerra e Paz\"?","resposta":"LIEVTOLSTOI"},
   {"pergunta":"Qual é o processo de conversão de gás em plasma?","resposta":"IONIZAÇÃO"},
   {"pergunta":"Quem é considerado o \"pai da química\"?","resposta":"ROBERTBOYLE"},
   {"pergunta":"Qual é o elemento químico com o símbolo \"C\"?","resposta":"CARBONO"},
   {"pergunta":"Quem é o autor de \"O Grande Gatsby\"?","resposta":"FSCOTTFITZGERALD"},
   {"pergunta":"Qual é o processo de conversão de energia luminosa em energia química nas plantas?","resposta":"FOTOSSINTESE"},
   {"pergunta":"Quem é considerado o \"pai da psicologia\"?","resposta":"WILHELMWUNDT"},
   {"pergunta":"Qual é o elemento químico com o símbolo \"O\"?","resposta":"OXIGENIO"},
   {"pergunta":"Quem é o autor de \"Ulisses\"?","resposta":"JAMESJOYCE"},
   {"pergunta":"Qual é o processo de conversão de um gás em líquido?","resposta":"CONDENSAÇÃO"},
   {"pergunta":"Quem é conhecido como o \"pai da medicina\"?","resposta":"HIPOCRATES"},
   {"pergunta":"Qual é o elemento químico com o símbolo \"N\"?","resposta":"NITROGENIO"},
   {"pergunta":"Quem é o autor de \"O Sol é para Todos\"?","resposta":"HARPERLEE"},
   {"pergunta":"Qual é o processo de conversão de um líquido em gás?","resposta":"EVAPORAÇÃO"},
   {"pergunta":"Quem é considerado o \"pai da astronomia\"?","resposta":"NICOLAUCOPERNICO"},
   {"pergunta":"Qual é o elemento químico com o símbolo \"He\"?","resposta":"HELIO"},
   {"pergunta":"Quem é o autor de \"A Revolução dos Bichos\"?","resposta":"GEORGEORWELL"},
   {"pergunta":"Qual é o processo de conversão de um gás em plasma?","resposta":"IONIZAÇÃO"},
   {"pergunta":"Quem é conhecido como o \"pai da história\"?","resposta":"HERODOTO"},
   {"pergunta":"Qual é o elemento químico com o símbolo \"Si\"?","resposta":"SILICIO"},
   {"pergunta":"Quem é o autor de \"O Apanhador no Campo de Centeio\"?","resposta":"JDSALINGER"},
   {"pergunta":"Qual é o processo de conversão direta de um sólido em gás?","resposta":"SUBLIMAÇÃO"},
   {"pergunta":"Quem é considerado o \"pai da medicina moderna\"?","resposta":"PARACELSO"},
   {"pergunta":"Qual é o elemento químico com o símbolo \"P\"?","resposta":"FOSFORO"},
   {"pergunta":"Quem é o autor de \"Ensaio Sobre a Cegueira\"?","resposta":"JOSESARAMAGO"},
   {"pergunta":"Qual é o processo de conversão de um líquido em sólido?","resposta":"CRISTALIZAÇÃO"},
  ],
  [
   {"pergunta":"Quem é conhecido como o \"pai da psicologia analítica\"?","resposta":"CARLJUNG"},
   {"pergunta":"Qual é o elemento químico com o símbolo \"K\"?","resposta":"POTASSIO"},
   {"pergunta":"Quem é o autor de \"A Metamorfose\"?","resposta":"FRANZKAFKA"},
   {"pergunta":"Qual é o processo de conversão de um sólido diretamente em gás, sem passar pelo estado líquido?","resposta":"SUBLIMAÇÃO"},
   {"pergunta":"Quem é considerado o \"pai da teoria quântica\"?","resposta":"MAXPLANCK"},
   {"pergunta":"Qual é o processo de conversão de gás em plasma?","resposta":"IONIZAÇÃO"},
   {"pergunta":"Quem é conhecido como o \"pai da geometria\"?","resposta":"EUCLIDES"},
   {"pergunta":"Qual é o segundo planeta a partir do Sol?","resposta":"VENUS"},
   {"pergunta":"Quem é o autor de \"A Divina Comédia\"?","resposta":"DANTEALIGHIERI"},
   {"pergunta":"Qual é o processo de conversão direta de um sólido em gás?","resposta":"SUBLIMAÇÃO"},
   {"pergunta":"Quem é considerado o \"pai da computação\"?","resposta":"ALANTURING"},
   {"pergunta":"Qual é o elemento químico mais abundante no universo?","resposta":"HIDROGENIO"},
   {"pergunta":"Quem escreveu \"O Alquimista\"?","resposta":"PAULOCOELHO"},
   {"pergunta":"Qual é o processo de conversão de um gás em líquido?","resposta":"CONDENSAÇÃO"},
   {"pergunta":"Quem foi o físico teórico que desenvolveu a teoria da relatividade?","resposta":"ALBERTEINSTEIN"},
   {"pergunta":"Qual é o menor planeta do sistema solar?","resposta":"MERCURIO"},
   {"pergunta":"Quem é o autor de \"Cem Anos de Solidão\"?","resposta":"GABRIELGARCIAMARQUEZ"},
   {"pergunta":"Qual é o processo de conversão de energia luminosa em energia química nas plantas?","resposta":"FOTOSSINTESE"},
   {"pergunta":"Quem é considerado o \"pai da psicologia\"?","resposta":"WILHELMWUNDT"},
   {"pergunta":"Qual é o elemento químico com o símbolo \"O\"?","resposta":"OXIGENIO"},
   {"pergunta":"Quem é o autor de \"Ulisses\"?","resposta":"JAMESJOYCE"},
   {"pergunta":"Qual é o processo de conversão de um líquido em gás?","resposta":"EVAPORAÇÃO"},
   {"pergunta":"Quem é conhecido como o \"pai da psicologia analítica\"?","resposta":"CARLJUNG"},
   {"pergunta":"Qual é o elemento químico com o símbolo \"K\"?","resposta":"POTASSIO"},
   {"pergunta":"Quem é o autor de \"A Revolução dos Bichos\"?","resposta":"GEORGEORWELL"},
   {"pergunta":"Qual é o processo de conversão de um gás em plasma?","resposta":"IONIZAÇÃO"},
   {"pergunta":"Quem é considerado o \"pai da química\"?","resposta":"ROBERTBOYLE"},
   {"pergunta":"Qual é o elemento químico com o símbolo \"C\"?","resposta":"CARBONO"},
   {"pergunta":"Quem é o autor de \"O Grande Gatsby\"?","resposta":"F. SCOTTFITZGERALD"},
   {"pergunta":"Qual é o processo de conversão de um líquido em sólido?","resposta":"CRISTALIZAÇÃO"},
   {"pergunta":"Quem é conhecido como o \"pai da biologia\"?","resposta":"ARISTOTELES"},
   {"pergunta":"Qual é o elemento químico com o símbolo \"Ag\"?","resposta":"PRATA"},
   {"pergunta":"Quem é o autor de \"Guerra e Paz\"?","resposta":"LIEVTOLSTOI"},
   {"pergunta":"Qual é o processo de conversão de gás em plasma?","resposta":"IONIZAÇÃO"},
   {"pergunta":"Quem é considerado o \"pai da filosofia\"?","resposta":"SOCRATES"},
   {"pergunta":"Qual é o elemento químico com o símbolo \"He\"?","resposta":"HELIO"},
   {"pergunta":"Quem é o autor de \"A Revolução dos Bichos\"?","resposta":"GEORGEORWELL"},
   {"pergunta":"Qual é o processo de conversão de um sólido em gás?","resposta":"SUBLIMAÇÃO"},
   {"pergunta":"Quem é conhecido como o \"pai da biologia moderna\"?","resposta":"CHARLESDARWIN"},
   {"pergunta":"Qual é o elemento químico com o símbolo \"Na\"?","resposta":"SODIO"},
   {"pergunta":"Quem é o autor de \"O Estrangeiro\"?","resposta":"ALBERTCAMUS"},
   {"pergunta":"Qual é o processo de conversão de gás em plasma?","resposta":"IONIZAÇÃO"},
   {"pergunta":"Quem é considerado o \"pai da geometria analítica\"?","resposta":"RENEDESCARTES"},
   {"pergunta":"Qual é o elemento químico com o símbolo \"Li\"?","resposta":"LITIO"},
   {"pergunta":"Quem é o autor de \"O Processo\"?","resposta":"FRANZKAFKA"},
   {"pergunta":"Qual é o processo de conversão de um líquido em sólido?","resposta":"CRISTALIZAÇÃO"},
   {"pergunta":"Quem é conhecido como o \"pai da medicina\"?","resposta":"HIPOCRATES"},
   {"pergunta":"Qual é o elemento químico com o símbolo \"N\"?","resposta":"NITROGENIO"},
   {"pergunta":"Quem é o autor de \"O Sol é para Todos\"?","resposta":"HARPERLEE"},
   {"pergunta":"Qual é o processo de conversão de um líquido em gás?","resposta":"EVAPORAÇÃO"},
   {"pergunta":"Quem é considerado o \"pai da astronomia\"?","resposta":"NICOLAUCOPERNICO"},
   {"pergunta":"Quem é o autor de \"A Revolução dos Bichos\"?","resposta":"GEORGEORWELL"},
   {"pergunta":"Qual é o processo de conversão de gás em plasma?","resposta":"IONIZAÇÃO"},
   {"pergunta":"Quem é conhecido como o \"pai da história\"?","resposta":"HERODOTO"},
   {"pergunta":"Qual é o elemento químico com o símbolo \"Si\"?","resposta":"SILICIO"},
   {"pergunta":"Quem é o autor de \"O Apanhador no Campo de Centeio\"?","resposta":"JDSALINGER"},
   {"pergunta":"Qual é o processo de conversão direta de um sólido em gás?","resposta":"SUBLIMAÇÃO"},
   {"pergunta":"Quem é considerado o \"pai da medicina moderna\"?","resposta":"PARACELSO"},
   {"pergunta":"Qual é o elemento químico com o símbolo \"P\"?","resposta":"FOSFORO"},
   {"pergunta":"Quem é o autor de \"Ensaio Sobre a Cegueira\"?","resposta":"JOSESARAMAGO"},
   {"pergunta":"Qual é o processo de conversão de um líquido em sólido?","resposta":"CRISTALIZAÇÃO"},
   {"pergunta":"Quem é conhecido como o \"pai da psicologia analítica\"?","resposta":"CARLJUNG"},
   {"pergunta":"Qual é o elemento químico com o símbolo \"K\"?","resposta":"POTASSIO"},
  ],
  [
   {"pergunta":"Quem é o autor de \"A Revolução dos Bichos\"?","resposta":"GEORGEORWELL"},
   {"pergunta":"Qual é o processo de conversão de gás em plasma?","resposta":"IONIZAÇÃO"},
   {"pergunta":"Quem é considerado o \"pai da química\"?","resposta":"ROBERTBOYLE"},
   {"pergunta":"Qual é o elemento químico com o símbolo \"C\"?","resposta":"CARBONO"},
   {"pergunta":"Qual é o processo de conversão de um líquido em gás?","resposta":"EVAPORAÇÃO"},
   {"pergunta":"Quem é conhecido como o \"pai da biologia\"?","resposta":"ARISTOTELES"},
   {"pergunta":"Qual é o elemento químico com o símbolo \"Ag\"?","resposta":"PRATA"},
   {"pergunta":"Quem é o autor de \"Guerra e Paz\"?","resposta":"LIEVTOLSTOI"},
   {"pergunta":"Qual é o processo de conversão de gás em plasma?","resposta":"IONIZAÇÃO"},
   {"pergunta":"Quem é considerado o \"pai da filosofia\"?","resposta":"SOCRATES"},
   {"pergunta":"Qual é o elemento químico com o símbolo \"He\"?","resposta":"HELIO"},
   {"pergunta":"Quem é o autor de \"A Revolução dos Bichos\"?","resposta":"GEORGEORWELL"},
   {"pergunta":"Qual é o processo de conversão de um sólido em gás?","resposta":"SUBLIMAÇÃO"},
   {"pergunta":"Quem é conhecido como o \"pai da biologia moderna\"?","resposta":"CHARLESDARWIN"},
   {"pergunta":"Qual é o elemento químico com o símbolo \"Na\"?","resposta":"SODIO"},
   {"pergunta":"Quem é o autor de \"O Estrangeiro\"?","resposta":"ALBERTCAMUS"},
   {"pergunta":"Qual é o processo de conversão de gás em plasma?","resposta":"IONIZAÇÃO"},
   {"pergunta":"Qual é o elemento químico com o símbolo \"Li\"?","resposta":"LITIO"},
   {"pergunta":"Quem é o autor de \"O Processo\"?","resposta":"FRANZKAFKA"},
   {"pergunta":"Qual é o processo de conversão de um líquido em sólido?","resposta":"CRISTALIZAÇÃO"},
   {"pergunta":"Quem é conhecido como o \"pai da medicina\"?","resposta":"HIPOCRATES"},
   {"pergunta":"Qual é o elemento químico com o símbolo \"N\"?","resposta":"NITROGENIO"},
   {"pergunta":"Quem é o autor de \"O Sol é para Todos\"?","resposta":"HARPERLEE"},
   {"pergunta":"Qual é o processo de conversão de um líquido em gás?","resposta":"EVAPORAÇÃO"},
   {"pergunta":"Quem é considerado o \"pai da astronomia\"?","resposta":"NICOLAUCOPERNICO"},
   {"pergunta":"Qual é o processo de conversão de gás em plasma?","resposta":"IONIZAÇÃO"},
   {"pergunta":"Quem é conhecido como o \"pai da história\"?","resposta":"HERODOTO"},
   {"pergunta":"Qual é o elemento químico com o símbolo \"Si\"?","resposta":"SILICIO"},
   {"pergunta":"Qual é a capital da China?","resposta":"PEQUIM"},
   {"pergunta":"Quem é o autor de \"O Conde de Monte Cristo\"?","resposta":"ALEXANDREDUMAS"},
   {"pergunta":"Qual é o processo de conversão de um gás em líquido?","resposta":"CONDENSAÇÃO"},
   {"pergunta":"Quem é conhecido como o \"pai da teoria da relatividade\"?","resposta":"ALBERTEINSTEIN"},
   {"pergunta":"Quem é o autor de \"O Senhor das Moscas\"?","resposta":"WILLIAMGOLDING"},
   {"pergunta":"Qual é o elemento químico com o símbolo \"C\"?","resposta":"CARBONO"},
   {"pergunta":"Quem é conhecido como o \"pai da eletricidade\"?","resposta":"BENJAMINFRANKLIN"},
   {"pergunta":"Qual é a capital da Itália?","resposta":"ROMA"},
   {"pergunta":"Quem é o autor de \"A Letra Escarlate\"?","resposta":"NATHANIELHAWTHORNE"},
   {"pergunta":"Qual é o processo de conversão de um sólido diretamente em gás, sem passar pelo estado líquido?","resposta":"SUBLIMAÇÃO"},
   {"pergunta":"Quem é conhecido como o \"pai da filosofia ocidental\"?","resposta":"SOCRATES"},
   {"pergunta":"Qual é o elemento químico com o símbolo \"Na\"?","resposta":"SODIO"},
   {"pergunta":"Quem é o autor de \"O Médico\"?","resposta":"NOAHGORDON"},
   {"pergunta":"Qual é o processo de transferência de calor através do movimento de um fluido?","resposta":"CONVECÇÃO"},
   {"pergunta":"Quem é conhecido como o \"pai da psicanálise\"?","resposta":"SIGMUNDFREUD"},
   {"pergunta":"Qual é o elemento químico com o símbolo \"Hg\"?","resposta":"MERCURIO"},
   
   {"pergunta":"Qual é o processo de conversão de um líquido em gás?","resposta":"EVAPORAÇÃO"},
   {"pergunta":"Quem foi o líder político sul-africano e ativista contra o apartheid?","resposta":"NELSONMANDELA"},
   {"pergunta":"Qual é o elemento químico com o símbolo \"Au\"?","resposta":"OURO"},
   {"pergunta":"Quem é o autor de \"O Retrato de Dorian Gray\"?","resposta":"OSCARWILDE"},
   {"pergunta":"Qual é o processo de conversão de gás em plasma?","resposta":"IONIZAÇÃO"},
   {"pergunta":"Quem é conhecido como o \"pai da geologia\"?","resposta":"JAMESHUTTON"},
   {"pergunta":"Quem é o autor de \"Moby Dick\"?","resposta":"HERMANMELVILLE"},
  ],
  [
   {"pergunta":"Qual é o processo de conversão de um gás em líquido?","resposta":"CONDENSAÇÃO"},
   {"pergunta":"Quem é conhecido como o \"pai da filosofia moderna\"?","resposta":"RENEDESCARTES"},
   {"pergunta":"Qual é o elemento químico com o símbolo \"Ag\"?","resposta":"PRATA"},
   {"pergunta":"Quem é o autor de \"O Apanhador no Campo de Centeio\"?","resposta":"JDSALINGER"},
   {"pergunta":"Qual é o processo de conversão de gás em plasma?","resposta":"IONIZAÇÃO"},
   {"pergunta":"Quem é conhecido como o \"pai da biologia\"?","resposta":"ARISTOTELES"},
   {"pergunta":"Qual é o elemento químico com o símbolo \"Si\"?","resposta":"SILICIO"},
   {"pergunta":"Quem é o autor de \"Dom Quixote\"?","resposta":"MIGUELDECERVANTES"},
   {"pergunta":"Qual é o processo de conversão direta de um sólido em gás?","resposta":"SUBLIMAÇÃO"},
   {"pergunta":"Quem é conhecido como o \"pai da computação\"?","resposta":"ALANTURING"},
   {"pergunta":"Qual é o elemento químico mais abundante no universo?","resposta":"HIDROGENIO"},
   {"pergunta":"Quem escreveu \"O Alquimista\"?","resposta":"PAULOCOELHO"},
   {"pergunta":"Quantos planetas existem em nosso sistema solar?","resposta":"OITO"},
   {"pergunta":"Qual é o processo de conversão de um gás em líquido?","resposta":"CONDENSAÇÃO"},
   {"pergunta":"Quem foi o físico teórico que desenvolveu a teoria da relatividade?","resposta":"ALBERTEINSTEIN"},
   {"pergunta":"Qual é o menor planeta do sistema solar?","resposta":"MERCURIO"},
   {"pergunta":"Quem é o autor de \"Cem Anos de Solidão\"?","resposta":"GABRIEL GARCIAMARQUEZ"},
   {"pergunta":"Qual é o processo de conversão de energia luminosa em energia química nas plantas?","resposta":"FOTOSSINTESE"},
   {"pergunta":"Quem é considerado o \"pai da psicologia\"?","resposta":"WILHELMWUNDT"},
   {"pergunta":"Qual é o elemento químico com o símbolo \"O\"?","resposta":"OXIGENIO"},
   {"pergunta":"Quem é o autor de \"Ulisses\"?","resposta":"JAMESJOYCE"},
   {"pergunta":"Qual é o processo de conversão de um líquido em gás?","resposta":"EVAPORAÇÃO"},
   {"pergunta":"Quem é conhecido como o \"pai da psicologia analítica\"?","resposta":"CARLJUNG"},
   {"pergunta":"Qual é o elemento químico com o símbolo \"K\"?","resposta":"POTASSIO"},
   
   {"pergunta":"Qual é o processo de conversão de gás em plasma?","resposta":"IONIZAÇÃO"},
   {"pergunta":"Quem é considerado o \"pai da química\"?","resposta":"ROBERTBOYLE"},
   {"pergunta":"Qual é o elemento químico com o símbolo \"C\"?","resposta":"CARBONO"},
   {"pergunta":"Quem é o autor de \"O Grande Gatsby\"?","resposta":"F. SCOTTFITZGERALD"},
   {"pergunta":"Qual é o processo de conversão de um líquido em sólido?","resposta":"CRISTALIZAÇÃO"},
   {"pergunta":"Quem é conhecido como o \"pai da biologia moderna\"?","resposta":"CHARLESDARWIN"},
   {"pergunta":"Qual é o elemento químico com o símbolo \"Na\"?","resposta":"SODIO"},
   {"pergunta":"Quem é o autor de \"O Estrangeiro\"?","resposta":"ALBERTCAMUS"},
   {"pergunta":"Qual é o processo de conversão de gás em plasma?","resposta":"IONIZAÇÃO"},
   {"pergunta":"Quem é considerado o \"pai da geometria analítica\"?","resposta":"RENEDESCARTES"},
   {"pergunta":"Qual é o elemento químico com o símbolo \"Li\"?","resposta":"LITIO"},
   
  
   {"pergunta":"Quem é conhecido como o \"pai da medicina\"?","resposta":"HIPOCRATES"},
   {"pergunta":"Qual é o elemento químico com o símbolo \"N\"?","resposta":"NITROGENIO"},
   {"pergunta":"Quem é o autor de \"O Sol é para Todos\"?","resposta":"HARPERLEE"},
   {"pergunta":"Qual é o processo de conversão de um líquido em gás?","resposta":"EVAPORAÇÃO"},
   {"pergunta":"Quem é considerado o \"pai da astronomia\"?","resposta":"NICOLAUCOPERNICO"},
  
  
   {"pergunta":"Qual é o processo de conversão de gás em plasma?","resposta":"IONIZAÇÃO"},
   {"pergunta":"Quem é conhecido como o \"pai da história\"?","resposta":"HERODOTO"},
   {"pergunta":"Qual é o elemento químico com o símbolo \"Si\"?","resposta":"SILICIO"},
  
   {"pergunta":"Qual é o maior mamífero terrestre?","resposta":"ELEFANTEAFRICANO"},
   {"pergunta":"Quem é o autor de \"O Pequeno Príncipe\"?","resposta":"ANTOINEDESAINTEXUPERY"},
   {"pergunta":"Qual é o processo de conversão direta de um sólido em gás?","resposta":"SUBLIMAÇÃO"},
  

  
  ],
  [
   {"pergunta":"Qual é o elemento químico com o símbolo \"N\"?","resposta":"NITROGENIO"},
   {"pergunta":"Quem é conhecido como o \"pai da eletricidade\"?","resposta":"NIKOLATESLA"},
   {"pergunta":"Qual é a capital do Japão?","resposta":"TOQUIO"},
   {"pergunta":"Quem é o autor de \"O Lobo do Mar\"?","resposta":"JACKLONDON"},
   {"pergunta":"Qual é o processo de conversão de um gás em líquido?","resposta":"CONDENSAÇÃO"},
   {"pergunta":"Quem é conhecido como o \"pai da psicanálise\"?","resposta":"SIGMUNDFREUD"},
   {"pergunta":"Qual é o elemento químico com o símbolo \"Au\"?","resposta":"OURO"},
   {"pergunta":"Quem é o autor de \"Crime e Castigo\"?","resposta":"FIÓDOR DOSTOIEVSKI"},
   {"pergunta":"Qual é o processo de transferência de calor através do movimento de um fluido?","resposta":"CONVECÇÃO"},
   {"pergunta":"Quem é conhecido como o \"pai da filosofia ocidental\"?","resposta":"SOCRATES"},
   {"pergunta":"Qual é o elemento químico com o símbolo \"He\"?","resposta":"HELIO"},
   {"pergunta":"Quem é o autor de \"A Revolução dos Bichos\"?","resposta":"GEORGEORWELL"},
   {"pergunta":"Quantos planetas existem em nosso sistema solar?","resposta":"OITO"},
   {"pergunta":"Qual é o processo de conversão de gás em plasma?","resposta":"IONIZAÇÃO"},
   {"pergunta":"Quem é considerado o \"pai da geologia\"?","resposta":"JAMESHUTTON"},
   {"pergunta":"Quem é o autor de \"Moby Dick\"?","resposta":"HERMANMELVILLE"},
   {"pergunta":"Qual é o processo de conversão de um gás em líquido?","resposta":"CONDENSAÇÃO"},
   {"pergunta":"Quem é conhecido como o \"pai da filosofia moderna\"?","resposta":"RENEDESCARTES"},
   {"pergunta":"Qual é o elemento químico com o símbolo \"Ag\"?","resposta":"PRATA"},
   {"pergunta":"Quem é o autor de \"O Apanhador no Campo de Centeio\"?","resposta":"JDSALINGER"},
   {"pergunta":"Qual é o processo de conversão de gás em plasma?","resposta":"IONIZAÇÃO"},
   {"pergunta":"Quem é conhecido como o \"pai da biologia\"?","resposta":"ARISTOTELES"},
   {"pergunta":"Qual é o elemento químico com o símbolo \"Si\"?","resposta":"SILICIO"},
   {"pergunta":"Quem é o autor de \"O Conde de Monte Cristo\"?","resposta":"ALEXANDREDUMAS"},
   {"pergunta":"Qual é o processo de conversão de um sólido em gás?","resposta":"SUBLIMAÇÃO"},
   {"pergunta":"Quem é conhecido como o \"pai da teoria da relatividade\"?","resposta":"ALBERTEINSTEIN"},
   
   {"pergunta":"Qual é o processo de conversão direta de um sólido em gás?","resposta":"SUBLIMAÇÃO"},
   {"pergunta":"Quem é conhecido como o \"pai da teoria da evolução\"?","resposta":"CHARLESDARWIN"},
   {"pergunta":"Qual é o país com a maior área territorial do mundo?","resposta":"RUSSIA"},
   {"pergunta":"Quem é o autor de \"1984\"?","resposta":"GEORGEORWELL"},
  
  
   {"pergunta":"Qual é a capital do Japão?","resposta":"TOQUIO"},
   {"pergunta":"Quem é o autor de \"O Lobo do Mar\"?","resposta":"JACKLONDON"},
   {"pergunta":"Qual é o processo de conversão de um gás em líquido?","resposta":"CONDENSAÇÃO"},
   {"pergunta":"Quem é conhecido como o \"pai da psicanálise\"?","resposta":"SIGMUNDFREUD"},
   {"pergunta":"Qual é o elemento químico com o símbolo \"Au\"?","resposta":"OURO"},
   {"pergunta":"Quem é o autor de \"Crime e Castigo\"?","resposta":"FIODORDOSTOIEVSKI"},
   {"pergunta":"Qual é o processo de transferência de calor através do movimento de um fluido?","resposta":"CONVECÇÃO"},
   {"pergunta":"Quem é conhecido como o \"pai da filosofia ocidental\"?","resposta":"SOCRATES"},
   {"pergunta":"Qual é o elemento químico com o símbolo \"He\"?","resposta":"HELIO"},
   {"pergunta":"Quem é o autor de \"A Revolução dos Bichos\"?","resposta":"GEORGEORWELL"},
   {"pergunta":"Quantos planetas existem em nosso sistema solar?","resposta":"OITO"},
   {"pergunta":"Qual é o processo de conversão de gás em plasma?","resposta":"IONIZAÇÃO"},
   {"pergunta":"Quem é considerado o \"pai da geologia\"?","resposta":"JAMESHUTTON"},
  ],
  [
   {"pergunta":"Quem é o autor de \"Moby Dick\"?","resposta":"HERMANMELVILLE"},
   {"pergunta":"Qual é o processo de conversão de um gás em líquido?","resposta":"CONDENSAÇÃO"},
   {"pergunta":"Quem é conhecido como o \"pai da filosofia moderna\"?","resposta":"RENEDESCARTES"},
   {"pergunta":"Qual é o elemento químico com o símbolo \"Ag\"?","resposta":"PRATA"},
 
   {"pergunta":"Qual é o processo de conversão de gás em plasma?","resposta":"IONIZAÇÃO"},
   {"pergunta":"Quem é conhecido como o \"pai da biologia\"?","resposta":"ARISTOTELES"},
   {"pergunta":"Qual é o elemento químico com o símbolo \"Si\"?","resposta":"SILICIO"},
   {"pergunta":"Quem é o autor de \"O Conde de Monte Cristo\"?","resposta":"ALEXANDREDUMAS"},
   {"pergunta":"Qual é o processo de conversão de um sólido em gás?","resposta":"SUBLIMAÇÃO"},
   {"pergunta":"Quem é conhecido como o \"pai da teoria da relatividade\"?","resposta":"ALBERTEINSTEIN"},

   {"pergunta":"Qual é o processo de conversão direta de um sólido em gás?","resposta":"SUBLIMAÇÃO"},
   {"pergunta":"Quem é conhecido como o \"pai da teoria da evolução\"?","resposta":"CHARLESDARWIN"},
   {"pergunta":"Qual é o país com a maior área territorial do mundo?","resposta":"RUSSIA"},
   {"pergunta":"Quem é o autor de \"1984\"?","resposta":"GEORGEORWELL"},
 

   {"pergunta":"Qual é a capital do Japão?","resposta":"TOQUIO"},
   {"pergunta":"Quem é o autor de \"O Lobo do Mar\"?","resposta":"JACKLONDON"},
   {"pergunta":"Qual é o processo de conversão de um gás em líquido?","resposta":"CONDENSAÇÃO"},
   {"pergunta":"Quem é conhecido como o \"pai da psicanálise\"?","resposta":"SIGMUNDFREUD"},
   {"pergunta":"Qual é o elemento químico com o símbolo \"Au\"?","resposta":"OURO"},
   {"pergunta":"Quem é o autor de \"Crime e Castigo\"?","resposta":"FIODORDOSTOIEVSKI"},
   {"pergunta":"Qual é o processo de transferência de calor através do movimento de um fluido?","resposta":"CONVECÇÃO"},
   {"pergunta":"Quem é conhecido como o \"pai da filosofia ocidental\"?","resposta":"SOCRATES"},
   {"pergunta":"Qual é o elemento químico com o símbolo \"He\"?","resposta":"HELIO"},
   {"pergunta":"Quem é o autor de \"A Revolução dos Bichos\"?","resposta":"GEORGEORWELL"},
   {"pergunta":"Quantos planetas existem em nosso sistema solar?","resposta":"OITO"},
   {"pergunta":"Qual é o processo de conversão de gás em plasma?","resposta":"IONIZAÇÃO"},
   {"pergunta":"Quem é considerado o \"pai da geologia\"?","resposta":"JAMESHUTTON"},
   {"pergunta":"Quem é o autor de \"Moby Dick\"?","resposta":"HERMANMELVILLE"},
   {"pergunta":"Qual é o processo de conversão de um gás em líquido?","resposta":"CONDENSAÇÃO"},
   {"pergunta":"Quem é conhecido como o \"pai da filosofia moderna\"?","resposta":"RENEDESCARTES"},
   {"pergunta":"Qual é o elemento químico com o símbolo \"Ag\"?","resposta":"PRATA"},
 
   {"pergunta":"Qual é o processo de conversão de gás em plasma?","resposta":"IONIZAÇÃO"},
   {"pergunta":"Quem é conhecido como o \"pai da biologia\"?","resposta":"ARISTOTELES"},
   {"pergunta":"Qual é o elemento químico com o símbolo \"Si\"?","resposta":"SILICIO"},
   {"pergunta":"Quem é o autor de \"O Conde de Monte Cristo\"?","resposta":"ALEXANDREDUMAS"},
   {"pergunta":"Qual é o processo de conversão de um sólido em gás?","resposta":"SUBLIMAÇÃO"},
   {"pergunta":"Quem é conhecido como o \"pai da teoria da relatividade\"?","resposta":"ALBERTEINSTEIN"},
  
   {"pergunta":"Qual é o processo de conversão direta de um sólido em gás?","resposta":"SUBLIMAÇÃO"},
   {"pergunta":"Quem é conhecido como o \"pai da teoria da evolução\"?","resposta":"CHARLESDARWIN"},
   {"pergunta":"Qual é o país com a maior área territorial do mundo?","resposta":"RUSSIA"},
   {"pergunta":"Quem é o autor de \"1984\"?","resposta":"GEORGEORWELL"},
  

   {"pergunta":"Qual é a capital do Japão?","resposta":"TOQUIO"},
   {"pergunta":"Quem é o autor de \"O Lobo do Mar\"?","resposta":"JACKLONDON"},
   {"pergunta":"Qual é o processo de conversão de um gás em líquido?","resposta":"CONDENSAÇÃO"},
   {"pergunta":"Quem é conhecido como o \"pai da psicanálise\"?","resposta":"SIGMUNDFREUD"},
   {"pergunta":"Qual é o elemento químico com o símbolo \"Au\"?","resposta":"OURO"}
    // ... Outros níveis aqui ...
  ]
];
